setwd("../dataset/")
getwd()
library(tidyr)
a <- read.csv("cpj-database-mod.csv")
View(a)
a4 <- separate(a, Date, c("day", "month", "year"), sep = "-")
View(a4)
local_and_foreign <- table(a4$Local.Foreign)
View(local_and_foreign)
pie(local_and_foreign, main = "Are foreign journalists targeted more than local journalists?", col = c('azure', 'darksalmon', 'cyan2'))