setwd("../dataset/")
getwd()
library(tidyr)
library(ggplot2)
a <- read.csv("cpj-database-mod.csv")
View(a)
a4 <- separate(a, Date, c("day", "month", "year"), sep = "-")
View(a4)
plot <- ggplot(a4, aes(x = year, fill = Sex)) + theme_bw() + geom_bar() + labs(y = "Count", title = "Gender wise distribution of journalist deaths over the years")
print(plot)